### ISSUE TITLE
请问如何设置Host

### ISSUE THREAD

**Issue by chen9989** [EalenXie/gitlab-webhook-robot#1]
我在application.yaml文件里设置如下gitlab:
  enable: true
  host: http://8.19.0.2
  private-token: TJ
但实际容器启动时显示的Please fill in this address in your Gitlab Webhook: http://10.10.201.157:8787/actuator/gitlab/webhook

或者V2版本内是否支持修改host

**Comment by EalenXie** [comment]
其实是不影响的，Please fill in this address in your Gitlab Webhook是指你成功启动后配置的webhook地址

gitlab的配置地址是为了启用gitlab的功能，让项目能够调用gitlab的rest api，关闭ci，或者重启ci等功能

**Comment by EalenXie** [comment]
另外，v2的版本是全面的升级，主要是为了一个应用可以支持N个webhook

**Comment by chen9989** [comment]
感谢
